version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # Newer versions of Jetty and Jersey require Java 1.11
      - dependency-name: "jettyVersion"
        versions: ["10.+"]
      - dependency-name: "jerseyVersion"
        versions: ["3.+"]
