name: Auto Merge PRs

on:
  pull_request:

jobs:
  auto-merge-jorje:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.2
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_FILTER_AUTHOR: dangmai
          MERGE_FORKS: "false"
          MERGE_LABELS: automerge
          UPDATE_RETRY_SLEEP: 30000 # 30 seconds
