name: Auto Merge PRs

on:
  pull_request:

jobs:
  auto-merge-jorje:
    needs: test
    if: github.ref_name == 'updates/jorje'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_FILTER_AUTHOR: dangmai
          MERGE_FORKS: "false"
          MERGE_LABELS: ""
