name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew check
    - name: Create zip file
      if: github.ref == 'refs/heads/master'
      run: ./gradlew distZip
    - name: Get current time
      uses: srfrnk/current-time@master
      if: github.ref == 'refs/heads/master'
      id: current-time
      with:
        format: YYYYMMDD
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        artifacts: 'build/distributions/apex-ast-serializer.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: '${{ steps.current-time.outputs.formattedTime }}-${{ steps.buildnumber.outputs.build_number }}'
