name: Update Jorje

on:
  repository_dispatch:
    types:
      - manual-jorje-update
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  jorje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 11
      - name: Run create-jorje-jar.sh
        run: ./tools/create-jorje-jar.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.0
        with:
          commit-message: Updated jorje
          title: "Update jorje dependency"
          branch: updates/jorje
          token: ${{ secrets.PERSONAL_TOKEN }}
          labels: automerge
