name: Update Jorje

on:
  repository_dispatch:
    types: manual-jorje-update
  schedule:
    - cron: '0 1 * * *'

jobs:
  jorje:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run create-jorje-jar.sh
      run: ./tools/create-jorje-jar.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      with:
        commit-message: Updated jorje
        title: 'Update jorje dependency'
        branch: updates/jorje
